apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: mattbun
  namespace: flux-system
spec:
  interval: 1m
  url: https://mattbun.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-hello
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: generic
      version: '>=0.1.1'
      sourceRef:
        kind: HelmRepository
        name: mattbun
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
    image:
      repository: nginxdemos/hello
      tag: latest
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: default-nginx-hello-strip-prefix@kubernetescrd
      hosts:
        - paths:
            - path: /hello
              pathType: Prefix
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: nginx-hello-strip-prefix
  namespace: default
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /hello
